apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: ebs-static
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0f245aca44f2f5259
    fsType: ext4
