apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels: # These lables are replicaset labels, evey k8 resource can have lables.
    app: guestbook
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels: # these lables should match with pod labels.
      tier: frontend
      app: nginx
      environment: dev
  template: # this one is nothing but pos defination.
    metadata:
      labels: # These are the pos labels.
        tier: frontend
        app: nginx
        environment: dev
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
