apiVersion: v1
kind: Pod
metadata:
  name: spimle-pod
  namespace: roboshop # f you dont mention specific namspae, it will attach to default namespace.
spec: 
  containers:
  - name: nginx-simple
    image: nginx:1.14.2
    ports: 
    - containerPort: 80
