apiVersion: v1
kind: Pod
metadata:
  name: labels
  annotations:
    com.project.author: sivakumar_reddy
    com.project.name: roboshop
spec:
  containers:
  - name: nginx-labels
    image: nginx
    ports: 
    - containerPort: 80