apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
type: Opaque
data: 
  username: Z3NwdnNyCg==  
  password: YWJjZTEyMzQK   
---
apiVersion: v1
kind: Pod
metadata:
  name: config-pod-direct
spec:
  containers:
  - name: config-pod-direct
    image: nginx
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: secret-basic-auth
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-basic-auth
          key: password
